In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("sales_dirty.csv")

In [4]:
pd.DataFrame(df)

,OrderID,CustomerName,Email,City,Category,Product,Quantity,UnitPrice,PaymentType,OrderDate,Gender,Status
0,1001,rahul,rahul@gmail.com,Delhi,Electronics,Laptop,1.0,55000.0,UPI,2025-01-05,M,Delivered
1,1002,PRIYA,priya@gmail.com,Mumbai,Fashion,Shoes,2.0,2200.0,Card,2025-01-08,F,Delivered
2,1003,Aman,NaN,Del,Electronics,Headphones,1.0,1800.0,Cash,2025-01-10,M,Cancelled
3,1004,Neha,neha@gmail.com,Delhi,Grocery,Rice,5.0,70.0,UPI,2025-01-12,F,Delivered
4,1005,Vikas,vikas@gmail.com,Bengaluru,Electronics,Phone,1.0,28000.0,Card,2025-01-15,M,Delivered
5,1006,sana,sana@gmail.com,Mumbai,Fashion,Dress,1.0,1800.0,UPI,2025-01-18,F,Returned
6,1007,Rohit,rohit@gmail.com,Mum,Grocery,Oil,3.0,150.0,Cash,2025-01-20,M,Delivered
7,1008,Isha,isha@gmail.com,Delhi,Fashion,Bag,1.0,1200.0,Card,2025-01-22,F,Delivered
8,1009,Kabir,kabir@gmail.com,Lucknow,Electronics,Laptop,1.0,52000.0,UPI,2025-01-25,M,Delivered
9,1010,Meera,meera@gmail.com,Bengaluru,Grocery,Rice,10.0,68.0,Cash,2025-01-28,F,Delivered
10,1011,Arjun,arjun@gmail.com,Delhi,Electronics,Phone,2.0,27500.0,Card,2025-02-02,M,Delivered
11,1012,Pooja,pooja@gmail.com,Mumbai,Fashion,Shoes,1.0,2500.0,UPI,2025-02-04,F,Delivered
12,1013,Dev,dev@gmail.com,Del,Grocery,Oil,4.0,145.0,Cash,2025-02-06,M,Delivered
13,1014,Tanya,tanya@gmail.com,Lucknow,Electronics,Headphones,2.0,1750.0,Card,2025-02-09,F,Cancelled
14,1015,Imran,imran@gmail.com,Bengaluru,Fashion,Dress,2.0,1900.0,UPI,2025-02-11,M,Delivered
15,1016,Anaya,anaya@gmail.com,Mumbai,Grocery,Rice,8.0,72.0,Cash,2025-02-14,F,Delivered
16,1017,Karan,karan@gmail.com,Delhi,Electronics,Laptop,1.0,58000.0,Card,2025-02-17,M,Delivered
17,1018,ZOYA,zoya@gmail.com,Mumbai,Fashion,Bag,2.0,1100.0,UPI,2025-02-19,F,Returned
18,1019,Nikhil,nikhil@gmail.com,Bengaluru,Grocery,Oil,2.0,155.0,Cash,2025-02-22,M,Delivered
19,1020,Riya,riya@gmail.com,Lucknow,Fashion,Shoes,1.0,2300.0,Card,2025-02-25,F,Delivered
20,1021,Farhan,farhan@gmail.com,Delhi,Electronics,Phone,1.0,29000.0,upi,2025-03-01,M,Delivered
21,1022,Simran,simran@gmail.com,Mumbai,Fashion,Dress,1.0,2100.0,Card,2025-03-03,F,Delivered
22,1023,Yash,yash@gmail.com,Bengaluru,Grocery,Rice,6.0,75.0,Cash,2025-03-05,M,Delivered
23,1024,Aditi,aditi@gmail.com,Delhi,Electronics,Headphones,3.0,1600.0,UPI,2025-03-08,F,Delivered
24,1025,Manav,manav@gmail.com,Lucknow,fashion,Bag,1.0,1300.0,Card,2025-03-10,M,Cancelled
25,1026,Naina,naina@gmail.com,Mumbai,Grocery,Oil,5.0,140.0,UPI,2025-03-12,F,Delivered
26,1027,Raghav,raghav@gmail.com,Delhi,Electronics,Laptop,1.0,54000.0,Card,2025-03-15,M,Delivered
27,1028,Sara,sara@gmail.com,Bengaluru,Fashion,Shoes,2.0,2400.0,UPI,2025-03-17,F,Delivered
28,1029,Adil,adil@gmail.com,Mum,Grocery,Rice,4.0,70.0,Cash,2025-03-20,M,NaN
29,1030,Kavya,kavya@gmail.com,Lucknow,Fashion,Dress,1.0,2000.0,Card,2025-03-23,F,Delivered
30,1031,Rohan,rohan@gmail.com,Delhi,Electronics,Phone,1.0,26500.0,UPI,2025-04-01,M,Delivered
31,1032,Fatima,fatima@gmail.com,Mumbai,Fashion,Bag,1.0,1250.0,Card,2025-04-03,F,Delivered
32,1033,Ajay,ajay@gmail.com,Bengaluru,Grocery,Oil,6.0,148.0,Cash,2025-04-05,M,Delivered
33,1034,Diya,diya@gmail.com,Delhi,Electronics,Headphones,1.0,1850.0,UPI,2025-04-08,F,Returned
34,1035,Sameer,sameer@gmail.com,Lucknow,Fashion,Shoes,NaN,2600.0,Card,2025-04-10,M,Delivered
35,1036,Aarohi,aarohi@gmail.com,Mumbai,Grocery,Rice,12.0,69.0,Cash,2025-04-12,F,Delivered
36,1037,Harsh,harsh@gmail.com,Delhi,Electronics,Laptop,1.0,56000.0,Card,2025-04-15,M,Delivered
37,1038,Mahi,mahi@gmail.com,Bengaluru,Fashion,Dress,2.0,1950.0,UPI,2025-04-17,F,Delivered
38,1039,Sahil,sahil@gmail.com,Lucknow,Grocery,Oil,3.0,160.0,Cash,2025-04-20,M,Delivered
39,1040,Tara,tara@gmail.com,Mumbai,Electronics,Phone,1.0,NaN,UPI,2025-04-22,F,Delivered
40,1041,Nitin,nitin@gmail.com,Delhi,Fashion,Bag,2.0,1150.0,Card,2025-05-01,M,Delivered
41,1042,Hina,hina@gmail.com,Bengaluru,Grocery,Rice,7.0,73.0,Cash,2025-05-03,F,Delivered
42,1043,Parth,parth@gmail.com,Lucknow,Electronics,Headphones,2.0,1700.0,UPI,2025-05-05,M,Cancelled
43,1044,Jiya,JIYA@GMAIL.COM,Mumbai,Fashion,Shoes,1.0,2250.0,Card,2025-05-08,F,Delivered
44,1045,Omar,omar@gmail.com,Delhi,Grocery,Oil,4.0,152.0,Cash,2025-05-10,M,Delivered
45,1046,Pihu,pihu@gmail.com,Bengaluru,Electronics,Laptop,1.0,57000.0,UPI,2025-05-13,NaN,Delivered
46,1047,Kunal,kunal@gmail.com,Lucknow,Fashion,Dress,1.0,1850.0,Card,2025-05-15,M,Delivered
47,1048,Noor,noor@gmail.com,Mumbai,Grocery,Rice,9.0,71.0,Cash,2025-05-18,F,Delivered
48,1049,Irfan,irfan@gmail.com,Delhi,Electronics,Phone,1.0,28500.0,UPI,2025-05-20,M,Delivered
49,1050,Leena,leena@gmail.com,Bengaluru,Fashion,Bag,1.0,1350.0,Card,2025-05-22,F,Delivered
50,1001,rahul,rahul@gmail.com,Delhi,Electronics,Laptop,1.0,55000.0,UPI,2025-01-05,M,Delivered
51,1006,sana,sana@gmail.com,Mumbai,Fashion,Dress,1.0,1800.0,UPI,2025-01-18,F,Returned

# Basic Information of Dataset

In [5]:
df.shape

(52, 12)

In [6]:
df.head(10)

,OrderID,CustomerName,Email,City,Category,Product,Quantity,UnitPrice,PaymentType,OrderDate,Gender,Status
0,1001,rahul,rahul@gmail.com,Delhi,Electronics,Laptop,1.0,55000.0,UPI,2025-01-05,M,Delivered
1,1002,PRIYA,priya@gmail.com,Mumbai,Fashion,Shoes,2.0,2200.0,Card,2025-01-08,F,Delivered
2,1003,Aman,NaN,Del,Electronics,Headphones,1.0,1800.0,Cash,2025-01-10,M,Cancelled
3,1004,Neha,neha@gmail.com,Delhi,Grocery,Rice,5.0,70.0,UPI,2025-01-12,F,Delivered
4,1005,Vikas,vikas@gmail.com,Bengaluru,Electronics,Phone,1.0,28000.0,Card,2025-01-15,M,Delivered
5,1006,sana,sana@gmail.com,Mumbai,Fashion,Dress,1.0,1800.0,UPI,2025-01-18,F,Returned
6,1007,Rohit,rohit@gmail.com,Mum,Grocery,Oil,3.0,150.0,Cash,2025-01-20,M,Delivered
7,1008,Isha,isha@gmail.com,Delhi,Fashion,Bag,1.0,1200.0,Card,2025-01-22,F,Delivered
8,1009,Kabir,kabir@gmail.com,Lucknow,Electronics,Laptop,1.0,52000.0,UPI,2025-01-25,M,Delivered
9,1010,Meera,meera@gmail.com,Bengaluru,Grocery,Rice,10.0,68.0,Cash,2025-01-28,F,Delivered

In [7]:
df.tail()

,OrderID,CustomerName,Email,City,Category,Product,Quantity,UnitPrice,PaymentType,OrderDate,Gender,Status
47,1048,Noor,noor@gmail.com,Mumbai,Grocery,Rice,9.0,71.0,Cash,2025-05-18,F,Delivered
48,1049,Irfan,irfan@gmail.com,Delhi,Electronics,Phone,1.0,28500.0,UPI,2025-05-20,M,Delivered
49,1050,Leena,leena@gmail.com,Bengaluru,Fashion,Bag,1.0,1350.0,Card,2025-05-22,F,Delivered
50,1001,rahul,rahul@gmail.com,Delhi,Electronics,Laptop,1.0,55000.0,UPI,2025-01-05,M,Delivered
51,1006,sana,sana@gmail.com,Mumbai,Fashion,Dress,1.0,1800.0,UPI,2025-01-18,F,Returned

In [8]:
df.columns

Index(['OrderID', 'CustomerName', 'Email', 'City', 'Category', 'Product',
       'Quantity', 'UnitPrice', 'PaymentType', 'OrderDate', 'Gender',
       'Status'],
      dtype='object')

In [9]:
df.describe()

           OrderID   Quantity     UnitPrice
count    52.000000  51.000000     51.000000
mean   1024.653846   2.647059  11212.117647
std      14.921868   2.621629  19487.209874
min    1001.000000   1.000000     68.000000
25%    1011.750000   1.000000    153.500000
50%    1024.500000   1.000000   1800.000000
75%    1037.250000   3.000000   2550.000000
max    1050.000000  12.000000  58000.000000

In [10]:
df.isnull().sum()

OrderID         0
CustomerName    0
Email           1
City            0
Category        0
Product         0
Quantity        1
UnitPrice       1
PaymentType     0
OrderDate       0
Gender          1
Status          1
dtype: int64

In [11]:
df.duplicated().sum()

2

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       52 non-null     int64
 1   CustomerName  52 non-null     object
 2   Email         51 non-null     object
 3   City          52 non-null     object
 4   Category      52 non-null     object
 5   Product       52 non-null     object
 6   Quantity      51 non-null     float64
 7   UnitPrice     51 non-null     float64
 8   PaymentType   52 non-null     object
 9   OrderDate     52 non-null     object
 10  Gender        51 non-null     object
 11  Status        51 non-null     object
dtypes: float64(2), int64(1), object(9)
memory usage: 5.0+ KB

In [13]:
df.iloc[3:5,2:6]

             Email       City     Category Product
3   neha@gmail.com      Delhi      Grocery    Rice
4  vikas@gmail.com  Bengaluru  Electronics   Phone

In [ ]:
df.drop_duplicates().